//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nu34life.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class State
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public State()
        {
            this.Plans = new HashSet<Plan>();
            this.Drugs = new HashSet<Drug>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public int Height { get; set; }
        public int Weighr { get; set; }
        public int Glucose { get; set; }
        public bool Affiliate { get; set; }
        public System.DateTime Generated_day { get; set; }
        public System.DateTime Expiration { get; set; }
        public int Nutritionist_Id { get; set; }
        public int Patient_Id { get; set; }
    
        public virtual Nutritionist Nutritionist { get; set; }
        public virtual Patient Patient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Plan> Plans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Drug> Drugs { get; set; }
    }
}
