//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nu34life.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Suscription
    {
        public int Id { get; set; }
        public System.DateTime Payday { get; set; }
        public System.DateTime Ending_date { get; set; }
        public int Nutritionist_Id { get; set; }
        public int Membership_Id { get; set; }
    
        public virtual Membership Membership { get; set; }
        public virtual Nutritionist Nutritionist { get; set; }
    }
}
